server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: maiyuMain
          uri: http://47.95.192.148:8080  #目标服务地址
          predicates:
            - Path=/api/sys/**
  redis:
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: -1
    database: 0
    host: 47.95.192.148
    port: 6379
    timeout: 1000